template-after = ")"
template-before = "!TEMPLATE("

[[file]]
path = "/home/liam/.config/i3/config"
template = "i3.template"

[[file]]
path = "/home/liam/.config/rofi/theme.rasi"
template = "rofi.template"

[[file]]
path = "/home/liam/.config/xfce4/terminal/terminalrc"
template = "xfce4-terminal.template"

[set.grey]
dark-bg = "1a1a1a"
dark-highlighted = "1f1f1f"
dark-text = "999999"
light-bg = "adadad"
light-text = "4f4f4f"
red-bg = "57382E"
red-text = "FF7D54"

[set.red]
dark-bg = "440012"
dark-highlighted = "6F0723"
dark-text = "9A334F"
light-bg = "C5778C"
light-text = "6F0723"
red-bg = "055335"
red-text = "58937D"
